title:            Scribble
description:      A jekyll theme. Because I scribble.
url:              bearprada.github.io
signoff:          PRADA
disqus_shortname: pradas
facebook_appid:   1434763533491367
google_analytics: # set tracking, remove from /javascripts/basic.js if unwanted.

links:
  - name:         About
    url:          /about
  - name:         Blog
    url:          http://bearprada.blogspot.tw/
    external:     true
  - name:         Email
    url:          mailto:bear.prada@gmail.com
    external:     true
  - name:         GitHub
    url:          http://github.com/bearprada
    external:     true
highlighter:      pygments
permalink:        pretty
markdown:         redcarpet
redcarpet:
  extensions: ["smart", "no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]
